[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "setuptools-scm"]

[project]
name = "ml-cr-aniso"
version = "0.2.0"
description = "Identifying nearby sources of ultra-high-energy cosmic rays with deep learning"
requires-python = "==3.13.7"
dependencies = [
    "tensorflow~=2.20",
    "torch~=2.8.0",
    "torchvision~=0.23.0",
    "numpy~=2.3.3",
    "astropy~=7.1",
    "healpy==1.18.1",
    "matplotlib~=3.10.6",
    "pandas~=2.3.2",
    "ray[data,train,tune,serve]~=2.49.1",
    "aiohttp~=3.12.15",
    "aioredis~=2.0.1"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["pkg*"]
namespaces = false
